#!/usr/bin/env python3
"""Generate and validate Korean Android resources using only the stdlib.

Run from any directory. --check is read-only and fails on stale resources,
missing translations, duplicate IDs, malformed XML, or changed format arguments.
Technical resource values and identifiers are intentionally never translated.
"""
from __future__ import annotations
import argparse
from collections import Counter
from pathlib import Path
import re
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parent.parent
RES = ROOT / 'app/src/main/res'
SKIP = {'app_name', 'dark_theme_follow_system', 'tencent_files', 'tencent_configs', 'cool_black'}
FORMAT = re.compile(r'%(?:\d+\$)?[-#+ 0,(<]*\d*(?:\.\d+)?[a-zA-Z%]')


def android_text(value: str) -> str:
    # TSV stores Android escapes (including literal \\n), not Python escapes.
    return re.sub(r'(?<!\\)([\'\"])', r'\\\1', value)


def xml_bytes(root: ET.Element) -> bytes:
    ET.indent(root, space='    ')
    return ET.tostring(root, encoding='utf-8', xml_declaration=True) + b'\n'


def load_translations() -> dict[str, str]:
    translations: dict[str, str] = {}
    for path in sorted((ROOT / 'localization/ko').glob('*.tsv')):
        for lineno, line in enumerate(path.read_text(encoding='utf-8').splitlines(), 1):
            if not line.strip() or line.startswith('#'):
                continue
            if '\t' not in line:
                raise ValueError(f'{path.name}:{lineno}: expected key<TAB>translation')
            key, value = line.split('\t', 1)
            key = key.strip()
            if not re.fullmatch(r'[A-Za-z_][A-Za-z0-9_]*', key):
                raise ValueError(f'{path.name}:{lineno}: invalid key {key!r}')
            if key in translations:
                raise ValueError(f'{path.name}:{lineno}: duplicate key {key}')
            if not value.strip():
                raise ValueError(f'{key}: empty translation')
            if re.search(r'[\u4e00-\u9fff]', value):
                raise ValueError(f'{key}: untranslated Chinese text')
            translations[key] = value
    return translations


def outputs() -> tuple[dict[Path, bytes], int]:
    translations = load_translations()
    base_path = RES / 'values/strings.xml'
    base_text = base_path.read_text(encoding='utf-8')
    base = ET.fromstring(base_text)
    source = {entry.attrib['name']: entry for entry in base if entry.tag == 'string'}
    if len(source) != len(base):
        raise ValueError('Unexpected resource type or duplicate source key')
    expected = set(source) - SKIP
    if set(translations) != expected:
        raise ValueError(f'Missing: {sorted(expected - set(translations))}; unknown: {sorted(set(translations) - expected)}')
    ko = ET.Element('resources')
    ko.append(ET.Comment(' Generated by localization/generate.py; edit localization/ko/*.tsv. '))
    for key, entry in source.items():
        if key in SKIP:
            continue
        value = translations[key]
        before = Counter(FORMAT.findall(entry.text or ''))
        after = Counter(FORMAT.findall(value))
        if before != after:
            raise ValueError(f'{key}: format arguments differ: {before} != {after}')
        attrs = {k: v for k, v in entry.attrib.items() if k != 'translatable'}
        ET.SubElement(ko, 'string', attrs).text = android_text(value)
        if entry.get('translatable') == 'false':
            old = re.compile(r'(<string\s+name="' + re.escape(key) + r'")\s+translatable="false"')
            base_text, count = old.subn(r'\1', base_text)
            if count != 1:
                raise ValueError(f'{key}: unable to restore translatability')
    arrays = ET.Element('resources')
    arr = ET.SubElement(arrays, 'string-array', {'name': 'statusbar_control_center_date_fix_lunar_horizontal_entries'})
    for value in ['@string/common_words_default', '텍스트 스크롤', '배치 위치 조정']:
        ET.SubElement(arr, 'item').text = value
    result = {
        base_path: base_text.encode('utf-8'),
        RES / 'values-ko/strings.xml': xml_bytes(ko),
        RES / 'values-ko/arrays.xml': xml_bytes(arrays),
    }
    for data in result.values():
        ET.fromstring(data)
    return result, len(translations)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    files, count = outputs()
    stale = []
    for path, data in files.items():
        if path.exists() and path.read_bytes() == data:
            continue
        if args.check:
            stale.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(data)
    if stale:
        raise SystemExit('Generated resources are missing or stale: ' + ', '.join(stale))
    print(f'Korean resource coverage: {count}/{count}; format arguments and XML validated.')


if __name__ == '__main__':
    main()
